aws/alb.go

use /kube-system/healthz (see https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L46)

change healthcheck path

---

aws/adapter.go
aws/alb.go

Should fix #13. I will test it tomorrow and see if it covers all the cases.

Added cluster ID

---

MAINTAINERS

Added MAINTAINERS file

---

.gitignore
aws/adapter.go
aws/alb.go
aws/alb_test.go
aws/asg_test.go
aws/asgmock_test.go
aws/awsmock_test.go
aws/ec2.go
aws/ec2_test.go
aws/ec2mock_test.go
aws/elbv2mock_test.go

First set of tests for the aws pkg

---

README.md

Update README to mention External DNS instead of Mate.

Mate -> External DNS

---

deploy/requirements.md

fix IAM requirements in the docs

fix policy requirements for CF stack version

---

.travis.yml
README.md

fix #45 to get some, hopefully working, badges

add badges and change travis to do coveralls integration

---

deploy/README.md
deploy/skipper.yaml
example/README.md
example/simple/my-nginx-deploy.yaml
example/simple/my-nginx-ingress.yaml
example/simple/my-nginx-svc.yaml

fix #37 and make the deployment for #18 more clear

add docs how to setup and how to run a simple test

---

deploy/requirements.md

remove duplicated requirement DescribeVpcs

---

.zappr.yml

add team for compliance reasons

make us "compliant"

---

.zappr.yaml

Take 3!
This will make it truly compliant by using the configuration defined by Torch.

Use correct config for .zappr.yaml

---

delivery.yaml

Pretty release condition in delivery.yaml

Pretty release condition in delivery.yaml

---

aws/cf.go
aws/doc.go
certs/doc.go

add godoc and fix generate statement should not be shown in godoc page

add package godoc 

---

README.md

test gh version badge

---

README.md
deploy/README.md
deploy/examples/sample-app-v1.yaml
deploy/examples/sample-app-v2.yaml
deploy/examples/sample-ing-traffic.yaml
deploy/examples/sample-ing-v1.yaml
deploy/examples/sample-ing-v2.yaml
deploy/examples/sample-svc-v1.yaml
deploy/examples/sample-svc-v2.yaml
deploy/ingress-controller.yaml
deploy/kops.md
deploy/skipper.yaml
deploy/test-deployment.md

added docs for kops with examples and renew skipper and ingress controller deployments

document kops deployment

---

README.md
deploy/README.md
deploy/test-deployment.md

fix broken links

---

deploy/kops.md

Fix broken link on kops.md

---

deploy/skipper.yaml

doc fix for skipper deployment

---

controller.go
worker.go

Add flag `-disable-sni-support` for disabling SNI support.
Fixes part of #129

Make it possible to disable SNI

---

controller.go
worker.go

This makes the certificate TTL (which indicate how long a certificate should be attached to an old load balancer) configurable.
It also changes the default time from 5 minutes to 30 minutes to ensure old ALBs are kept while DNS is migrated giving clients connecting to a service an ingress more time to migrate between ALBs.

Make certificate TTL configurable. Set default to 30m

---

deploy/kops.md

`$sgidingress--tags` > `$sgidingress --tags` - missing space was causing an error. 
also changed the way on how to give keys and values.

fixing typo and improved the create-tags part

---

Makefile
controller.go

Add version printing with more context. The old did not work, because of miss match package within the LDFLAGS

--version prints version githash and buildstamp

---

aws/cf.go
glide.lock
worker.go

Fix nil ptr deref

---

deploy/kops.md

lookup vpcid using the cli

---

aws/adapter.go
aws/cf.go
aws/cf_template.go
controller.go

implements feature #155 set connection idle timeout for created ALBs

set connection idle timeout for created ALBs

---

README.md
kubernetes/adapter.go
kubernetes/adapter_test.go
kubernetes/ingress.go

remove zalando.org/aws-load-balancer-ssl-cert-domain annotation
This will fix #149

remove zalando.org/aws-load-balancer-ssl-cert-domain

---

README.md

fix doc refereing a flag that does not exist.

Refer to `-controller-id` flag, not -`operator-id`

---

worker.go

This is a purely cosmetic change to make the code more understandable. The `managedItem` name was always confusing. It really describes a load balancer, so let's call it that!

Rename managedItem to loadBalancer

---

delivery.yaml

Update delivery yaml to new format

Update delivery yaml to new format

---

worker.go

show number of certs found

---

certs/caching.go
controller.go

#207  added a flag to blacklist certificate ARNs, that will not be considered from the controller

added a flag to blacklist certificate ARNs

---

aws/adapter.go
aws/cf.go
aws/cf_template.go
controller.go

add dualstack support

---

README.md

add a target link to release

---

README.md

Fix link to example deployment

Fix link to example deployment

---

README.md

I would say we have enough production experience at Zalando to update the README accordingly.

update project status: consider it battle-tested

---

deploy/ingress-serviceaccount.yaml

Reduce RBAC role to only what is needed.

Reduce RBAC role to only what is needed

---

aws/adapter.go
aws/cf.go
controller.go
kubernetes/adapter.go
kubernetes/adapter_test.go
kubernetes/ingress.go
kubernetes/ingress_test.go
worker.go
worker_test.go

Fixes https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/206
Fixes https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/23

Security group annotation support 

---

worker.go
worker_test.go

Part of increasing test coverage initiative.

Add more unit tests

---

deploy/requirements.md

- Fixed iam policy `Getertificate` → `GetCertificate`

fixed typo iam policy

---

aws/adapter.go
aws/ec2.go
certs/caching.go
certs/matching.go
controller.go
go.mod
go.sum
worker.go

based on #231
to be up2date with master branch and prevent conflicts
- changed logging to logrus
- implemented debugFlag (--debug)
fixes #89

logging level & debug logging option

---

controller.go
worker.go

simple hack to support https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/157

trigger CF stack update on first iteration

---

aws/adapter.go
aws/ec2.go

This would have saved me a couple of hours today ;)

Log when security group cannot be found

---

aws/asg.go

This limits the number of TGs the controller will try to attach to an ASG in each APi call. The limit is 10 because this is the limit in the AWS api.
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_AttachLoadBalancerTargetGroups.html
Without this the controller can get stuck unable to update ASGs if you have many load balancers.

Chunk number of TGs attached to ASG

---

README.md
aws/adapter.go
aws/adapter_test.go
aws/asg.go
aws/asg_test.go
controller.go

This PR is to address issue #266 and obsoletes PR #275.
It should not cause a regression to the patches which caused this regression. :)
Signed-off-by: Joe Hohertz <joe@viafoura.com>

Rework fix for CUSTOM_FILTERS

---

README.md

Remove `dep` from readme

---

delivery.yaml

fix image path

---

.travis.yml

Only updating golangci version

Updating golangci

---

README.md
kubernetes/adapter.go
kubernetes/adapter_test.go

Do not ignore empty ingress class

---

go.mod
go.sum

this PR fixes #300
Signed-off-by: Marius Voila <myself@mariusv.com>

bumping aws-sdk-go version to support me-south-1 region

---

kubernetes/adapter.go
kubernetes/client.go
kubernetes/routegroup.go

fix #312 - make RouteGroup CRD optional and log a warning to notify the user about RouteGroups

RouteGroup CRD should be optional

---

go.mod
go.sum

Good to keep this up to date as they have fixed some things related to IMDSv2.

Update aws-sdk-go v1.29.34

---

aws/adapter.go
controller.go
kubernetes/adapter.go
kubernetes/client.go

Fixes #309
See https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/309#issuecomment-607275390

Add flag to disable instrumented http client

---

aws/adapter.go
aws/ec2.go
controller.go

Makes it easier to debug when things go wrong.

Add more debug logs to show what is happening

---

.github/workflows/ci.yaml

Github Actions

---

certs/caching_test.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Add caching unittest

---

aws/cf_template.go
controller.go
go.mod
go.sum

Related to https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/320
Added support for WAF v2, based on the parameter when it is an ARN of WAF2 it will create the right template

#320 Added support for WAF v2 based on waf parameter

---

README.md
aws/adapter.go
aws/cf.go
aws/cf_template.go
aws/cf_template_test.go
aws/cf_test.go
certmock_test.go
controller.go
kubernetes/adapter.go
kubernetes/adapter_test.go
kubernetes/ingress.go
worker.go
worker_test.go

LB-WAF association from ingress

---

README.md

Hi, stumbled upon this small detail. BR, Alessandro

Small typo regarding code formatting

---

.github/workflows/ci.yaml

fix GH action

---

Dockerfile

Use compliant base image

---

README.md

Delayed deletion is not mentioned in README and can be cause for confusion. #203

Add note about stack deletion delay in README.nd

---

deploy/requirements.md

Adds missing IAM permisisons `elasticloadbalancing:ModifyTargetGroupAttributes`
Fix #408

Add missing IAM permission: ModifyTargetGroupAttributes

---

worker.go
worker_test.go

If a certificate defined on a stack is manually deleted from ACM the controller will end up in a situation where it keeps the certificate on the stack and continuously tries to update the stack which fails because of the non-existing certificate.
This PR aims to resolve this by checking if the certificate still exists when it builds an internal representation of the load balancer based on the stack, if it no longer exists it's not added and will be removed from the stack in the next update.
Additionally to this we also need to run the controller with a lower `--cert-polling-interval` to reduce the time where the controller thinks a deleted certificate exists. I don't change the default (`30m`) in this PR, but we may consider changing it after running with a lower value in Zalando for some …

Handle deleted certs by removing them from the LB stacks

---

worker.go

Fixes problem logging

---

kubernetes/pods.go
kubernetes/pods_test.go

There is a corner case where the initial listing of the pods happens during an ingress pod start phase. A pod without an assigned IP address might be included then, causing an ALB TG update error.
We are validating the pod statuses in the informer event handler but not yet at the initial listing. Adding the same validations there as well.

CNI mode: validate initial pod list

---

aws/iam_test.go
kubernetes/adapter_test.go
kubernetes/client.go
kubernetes/client_test.go
kubernetes/config.go
kubernetes/config_map.go
kubernetes/ingress.go
kubernetes/ingress_test.go
kubernetes/routegroup.go
kubernetes/routegroup_test.go

replace ioutil with new functions

---

kubernetes/adapter.go
kubernetes/adapter_test.go
worker.go

worker: log Ingress resource type

---

controller.go
kubernetes/adapter.go
kubernetes/adapter_test.go
worker.go
worker_test.go

Add routegroup and fabricgateway count metrics

---

worker.go

worker: remove logs in favor of metrics

---

controller.go
metrics.go
worker.go

metrics: add change counters

---

.github/workflows/gh-packages.yaml

Fixes https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/562
Signed-off-by: Mustafa Abdelrahman <mustafa.abdelrahman@zalando.de>

Add workflow for github packages

---

README.md
deploy/ingress-controller.yaml.example

move image registry from registry.opensource.zalan.do to GHCR

---

aws/adapter_test.go
aws/asg_test.go
aws/cf_template.go
aws/cf_test.go
aws/ec2_test.go
certs/doc.go
kubernetes/doc.go
worker_test.go

With `make fmt` & `find . -name '*.go'  | xargs -I{} gopls check {}`

Clean `gopls` warnings and run `make fmt`

---

delivery.yaml

* Fixes the image build such that an image is built and pushed from a PR
* Update the base image for Zalando private images to the latest alpine image (alpine-3).

Fix image build on PR

---

certs/fake/certificate.go
worker_test.go

Follow up on https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/587
Separate certificate mock to another package.

Move certificate mock to another package

---

aws/ec2.go

Fix security group auto-discovery filter

---

worker.go

worker: log ingress details without matching certificate

---

aws/cf_template.go
aws/cf_template_test.go
testdata/ingress_nlb/output/templates/ing.cf
testdata/ingress_rg_shared_nlb/output/templates/shared.cf
testdata/rg_nlb/output/templates/rg.cf

fix: disabling NLB cross zone load balancing had no effect on current NLBs

fix: disabling NLB cross zone load balancing had no effect on current NLBs

---

README.md
deploy/kops.md
deploy/requirements.md

doc: add requirements for acm tagging
doc: add missing documented features to the list

doc: add requirements for acm tagging

---

delivery.yaml

Signed-off-by: Mustafa Abdelrahman <mustafa.abdelrahman@zalando.de>

containerization: use `amazonlinux-2023` base image for better security

---

.github/dependabot.yml
kubernetes/pods.go

- github: group update gomod
- github: add docker update
- github: add GH Actions update

github: group update gomod

---

Makefile
internal/aws/cloudformation/schema.go

Update to latest version 206.0.0
Updates https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/459
Updates https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/495

internal/aws/cloudformation: update CloudFormation schema

---

.github/workflows/gh-packages.yaml

update actions to go 1.25
