- aws/alb.go
We should refactor the code to make it possible to configure the port. This require some changes in the way the options are read. For the moment, we just pick a different port for the sake of testing.
> Changed default port before making it configurable

- aws/alb.go
In case there are no loadbalancers at all `findManagedLoadBalancers`
should just return with `ErrLoadBalancerNotFound`.
> Return ErrLoadBalancerNotFound when there are no lbs

- kubernetes/client_test.go
some build hosts are slower than the previous timeout
> increased the timeout for the test

- aws/adapter.go
- aws/alb.go
This adds an http listener to all ALBs created by the ingress controller.
This makes it possible to redirect http->https (assuming skipper does the redirect.)
It addresses part of #12 but not all. It does not enable the creation of
HTTP only load balancers because the certificate arn is still used to
determine whether the ALB should exist or not.
Also, it will not create the http listener on existing ALBs, so we will have to add them manually when rolling this out.
> Add http listener to ALBs

- aws/adapter.go
- aws/alb.go
#28 introduced two bugs related to deleting an ALB managed by the
controller. First bug was attempting to detach the target group from the
ASG twice. Second bug was not initializing the http listener struct when
getting an ALB, this meant the http listener was never deleted from the
ALB and thus the ALB deletion failed because of the active listener
resource.
This fixes both of those issues.
@lmineiro thanks for the heads up! Please take a look.
I'm fine with merging #26 first and then add the related tests to this PR.
> Fix deleting LB managed by controller

- aws/alb.go
- aws/alb_test.go
normalizeLoadBalancerName() could return an invalid name
> fix normalize name could return an invalid name

- aws/alb.go
Check health every 10s to become unhealthy within 30s (default pod grace period).
This is required in combination with https://github.com/zalando/skipper/pull/307 to make the ALB consider the node unhealthy quick enough.
> Health check interval 10s

- aws/alb.go
- aws/alb_test.go
If we get rate limited in the call to DescribeLoadBalancer we could end up with a wrong list of ALBs, which would trigger an ALB create.
> Fail fast if DescribeListeners returns error

- aws/adapter.go
- controller.go
- glide.lock
- glide.yaml
- kubernetes/client.go
Just an idea how we can see how many requests to AWS and Kubernetes API we make.
Gives you something like this
```
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.5"} 66904
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.9"} 174219
http_request_duration_microseconds{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200",quantile="0.99"} 508884
http_request_duration_microseconds_sum{handler="instrumented_http",host="10.3.0.1:443",method="GET",path="ingresses",query="",scheme="https",status="200"} …
```
> Collect metrics about issued API requests

- deploy/requirements.md
- worker.go
After refactoring 
* [bugfix] 1 ALB can have multiple ingress objects, so we have to update ingresses status field for all of them
* [log] add some more logs
> Add logs and fix 1:n for alb:ingress

- glide.lock
- glide.yaml
This updates the dependencies of the project, in particular: 
- update AWS SDK to latest version - this deserves testing 
- updates https://github.com/linki/instrumented_http to latest, the version previously used had poor error handling, (see https://github.com/linki/instrumented_http/blob/v0.1.0/client.go#L63) 
- removes unneeded dependency on spew (not used in tests anymore)
> updated dependencies of the project

- delivery.yaml
- CDP Steps for Kube-Ingress-Controller on AWS
> CDP Build Steps

- Dockerfile
- Makefile
- README.md
- delivery.yaml
- deploy/ingress-controller.yaml
This uses Docker's new multi-stage dockerfiles to build.
It builds the binary inside a Docker containe and avoids cluttering the host machine with stuff. By using the new build stages this can conveniently be run with a simple `docekr build`.
unrelated: I consistently change any reference to the project to `kube-ingress-aws-controller`.
> build image using multi-stage builds

- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/cfmock_test.go
- worker.go
fix for #68 : implement deleteScheduled tag to postpone deletion of ALBs 1 hour after trigger
to be discussed with @njuettner
> safely delete stack

- delivery.yaml
This configures the delivery.yaml to build build and push images also for PRs. Images build from PRs will have a `-test` suffix so they don't clash with images produced from `master`.
It also changes the tag used for images build on master to use the `RELEASE_VERSION` (commit hash or tag) instead of `CDP_BUILD_VERSION`.
> Build image on PR and use RELEASE_VERSION for master pushes

- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- controller.go
- worker.go
To fix migrations, for example 2AZs to 3AZs we have to update all CF stacks which we currently have.
This PR is not ready yet, because we need to have a flag to enable migrations or another goroutine which does the updateStack calls in a slower iteration than every minute.
> update-stack on ready CFs

- Makefile
Since we have docker multistage build in place, building the application on the host is not needed anymore
> Build.docker should not depend on build.linux

- Dockerfile
Use the `latest` golang docker image as build image which always resolves to the current stable release of Go.
I consider Go stable enough that it's ok to not pin the build to a particular version, but instead automatically build against the latest stable version.
> Always build against latest stable Go version

- README.md
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
Supports specifying domain for matching a cert via the
`zalando.org/aws-load-balancer-ssl-cert-domain` annotation.
This partly solves #81 by supporting the use case for a single domain.
/cc @szuecs
> Support specifying cert domain via annotation

- .travis.yml
Updates the go version used in travis to the latest stable version (1.9) and allows builds for go tip version to fail.
> Update go version used in travis, allow tip to fail

- worker.go
Checks that the ARN specified in the `zalando.org/aws-load-balancer-ssl-cert` annotation exists in the account before creating a stack. If it doesn't exist then no stack/ALB is created and an error is logged.
This ensures that the ingress-controller doesn't create/delete ALBs forever if a user specifies the wrong ARN.
Fix #86 (Not possible to set an error status on the ingress object, so it just logs the error).
> Check that specified certificate ARN exists before creating stack

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/ec2.go
- aws/ec2_test.go
- deploy/requirements.md
Uses the 'official' `kubernetes.io/cluster/<cluster-id>` tag for discovery to not depend on custom tags.
This is sort of a breaking change in the sense that existing ALBs will be disowned by the ingress controller (because of the replaced `ClusterID` tag) and new ALBs using the `kubernetes.io/cluster/<cluster-id>` will be setup instead. This means a manual cleanup of old ALBs is required.
The cleanup is a one-time task and thus I did not put effort into adding it to the controller itself as it would be a significant change.
Fix #77 
Somewhat related to #95
> Use kubernetes.io/cluster/<cluster-id> tag for discovery

- aws/ec2.go
- aws/ec2_test.go
This adds support for the legacy KubernetesCluster tag as a fallback
when detecting clusterID from the host instance.
This is to support kops which still use the old tag for the ec2
instances.
The new tag kubernetes.io/cluster/<cluster-id> will still be used and
expected by the ingress controller for the security group and the stack
that is created.
> Add support for legacy KubernetesCluster tag

- aws/adapter.go
- aws/ec2.go
- aws/ec2_test.go
- aws/ec2mock_test.go
This limits the found subnets to the ones tagged with either `kubernetes.io/role/elb` or `kubernetes.io/role/internal-elb` in order to control which subnets are picked in case there are many.
If no subnet is tagged with either annotation then we assume there's no need to identify them and return the entire list. This is equivalent to the current behaviour.
Fixes: https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/102
> Limit to tagged ELB subnets if found

- README.md
- aws/adapter.go
- aws/cf.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- worker.go
Related to the [Support "internal" Application Load Balancers](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/22) issue.
I add a zalando annotation to select internet-facing (default) or internal scheme to ELB
> Add annotation to select scheme for elb creation

- deploy/skipper.yaml
spec in template section was missing, such that we got a validation error in #106
> spec error in deploy example

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/naming.go
- aws/naming_test.go
- worker.go
This groups ingresses by loadbalancer scheme. Without grouping them the controller would create a single ALB for two ingresses with different schemes assuming the certificate was the same.
Fixes #114
> Group ingresses by ingress scheme

- README.md
- aws/adapter.go
- aws/adapter_test.go
- aws/ec2.go
- aws/ec2_test.go
- controller.go
This changes the logic of selecting subnets for the ALB to match the logic used
by the kube-controller-manager when selecting subnets for ELBs used for
services of type LoadBalancer.
This solves several problems:
1. The controller will no longer try to create an ALB with multiple subnets of
the same AZ. (Fixes #108)
2. If only some subnets are tagged with the elb role the controller will favour
those with the tag but not limit the selection to only those with a tag.
3. Favour using internal subnets for ALBs with the scheme `internal`.
Fix #108
> Predictably select subnets

- .travis.yml
This is similar to what we do for the Dockerfile build. (we always use the latest stable version of go automatically).
> Always tests against latest go stable version

- aws/adapter.go
- aws/asg.go
- aws/asg_test.go
- aws/asgmock_test.go
This ensures that obsolete Target Groups gets removed from the ASGs.
Fix #126
> Remove obsolete Target Groups from ASGs

- README.md
- aws/adapter.go
- aws/cf.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- worker.go
This adds an annotation `zalando.org/aws-load-balancer-shared: "false"` which, when set will make sure to provision an ALB that is unique for a single ingress resources. This is useful if a single application in the cluster has clients which doesn't support SNI or if it's getting so much traffic that it should not share the ALB with other applications.
It works by having a `ingress:owner=<namespace>/<ingress-name>` tag on the stacks which are reserved for a single ingress. If the annotation is later removed from the ingress the stacks will be re-aggregated.
Fix #129
> Make it possible to get a unique ALB for a single ingress resource

- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/cfmock_test.go
- controller.go
- deploy/requirements.md
- glide.lock
- glide.yaml
Adds flag for enabling stack termination protection on ALB stacks.
https://aws.amazon.com/about-aws/whats-new/2017/09/aws-cloudformation-provides-stack-termination-protection/
This is to have a bit more protection against users terminating infrastructure stacks in the AWS console.
> Add flag for enabling stack termination protection on ALB stacks

- aws/adapter.go
When there are no TargetGroups we should not update the targets.
Fix #139
> Don't update ASG when there are no targetgroups

- aws/naming.go
- aws/naming_test.go
This cleans up the stack nameing code a bit and introduces a new naming
format that should work in all cases:
```
kube-ingress-aws-controller-<clusterID>-<UUID>
```
This naming convention will not affect existing ALB stacks, it's only
applied to new stacks.
Fixes #144 and #146
> Streamline stack naming

- controller.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- kubernetes/ingress_test.go
- kubernetes/testdata/fixture01.json
Implements a new flag -ingress-class-filter which if specified is
interpreted as a comma seperated list of values which will be used
as a filter to match kubernetes.io/ingress.class annotations. If
the annotation is not set, or does match, the ingress will be hidden
from the ingress controller and not acted upon.
As of this commit the work passes a 'make test' but requires
further testing.
> Initial work for zalando-incubator/kube-ingress-aws-controller#38

- aws/cf_template.go
A bug in how CloudFormation processes updates for LBs can result in complete misconfiguration. The `AWS::ElasticLoadBalancingV2::Listener` resource must have exactly one certificate in the CertificateArn property, which is then treated as the default certificate. All the rest are managed in a separate resource of type `AWS::ElasticLoadBalancingV2::ListenerCertificate`. Unfortunately, the update is not performed atomically. CloudFormation updates the `Listener` first, and only after it's done it creates a new `ListenerCertificate` resource and deletes the old one.
However, if the previously default certificate swaps positions with one from the `ListenerCertificate` list, the resulting race conditions in AWS will result in a completely broken configuration. One of the certificates will be …
> Add a workaround for CloudFormation update issues

- aws/cf_template.go
Follow up of #162, apparently _ is unsupported in CF resource names. Fix an incorrect comment as well.
> Remove _ from CF resource name

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/ec2.go
- controller.go
This allows multiple instances of kube-aws-ingress-controller to coexist in the same cluster.
It allows to properly split different types of trafic or routers (using Skipper and another router) at the same time.
> Add support for multiple controller instances

- aws/adapter.go
- aws/ec2.go
- aws/ec2_test.go
This fixes #167 by adding a filter when collecting subnet IDs for the manifest structure.
> filter subnets on cluster ID tag before consideration

- README.md
- make a note that we deleted zalando.org/aws-load-balancer-ssl-cert-domain annotation
- add that you can Tag your EC2 subnet to favour alb creation in this
> docs: ec2 subnet tags and deleted annotation

- aws/adapter.go
- aws/asg.go
- aws/asg_test.go
- aws/elbv2mock_test.go
This makes sure that the controller only detaches target groups from ASGs when these target groups are managed/owned by the controller. The ownership is determined based on the clusterID and controllerID tags on the target groups.
Fix #165
> Only manage TGs that are owned by the controller

- controller.go
Make sure to use the value of the CLI flag `-health-check-interval` when
creating a new AWS adapter instance.
> Propagate health check interval CLI flag to AWS adapter

- aws/adapter.go
- controller.go
- worker.go
The objective of this PR is allowing setting the desired maximum number of certificates to be attached to the ALB with backwards compatibility.
Apart of giving flexibility, allowing to divide the requests among multiple ALBs, it helps to workaround the issue with CloudFormation described in https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/176
> Make maximum number of certificates per ALB configurable

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- controller.go
This allows the usage of routers that have different ports for upstream and health check ports.
It also makes clear the distinction between the health check port and the upstream one, as this PR started
when we were trying to have different routers in the same machine and we thought that the port 9999 was hardcoded.
The legacy behaviour of using the health check port as the upstream port is maintained for backward compatibility.
> Add support for using different health check and upstream ports

- aws/cf.go
Passes the target port parameter on stack update to ensure it doesn't
get reset to the default value in case a custom value was set by the
user.
Fix #189
> Pass target port on stack update

- aws/asg.go
- aws/asg_test.go
- aws/elbv2mock_test.go
In case an Ingress stack is deleted, the TargetGroup will also be
deleted, but not removed from the list of TargetGroups in the ASG.
This renders the ASG in a state where it can't spawn new instances
because it can't attach the non-existing TargetGroup.
To fix this, the controller will now look up all TargetGroups every time
it consider TargetGroups to attachment/detachment of an ASG.
Fix #197
> Detach non-existing target groups from ASGs

- deploy/README.md
- deploy/ingress-controller.yaml.example
- deploy/ingress-serviceaccount.yaml
- deploy/requirements.md
- deploy/skipper.yaml.example
- deploy/skipper_serviceaccount.yaml
Following Bug https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/182
Update docs to reflect how to use IPv6
Add RBAC rules to run properly the skipper and the ingress-controller
Update wrong elasticloadbalancingv2 policy rules
> Update documentation to support IPv6

- aws/adapter.go
- aws/ec2.go
- aws/ec2_test.go
- controller.go
This went a little deeper than initially expected, owing to the fact that where buildManifest was being called (and where the SGs are ultimately looked up), was *prior* to the application of the collected flag values to the awsAdapter.
So I've moved the manifest to something similar to the With*() functions, and apply it in the same way *after* we have the flags applied to the awsAdapter. Let me know if you'd like to see this handled differently?
I had not previously seen this, as I had always been running an instance with the default controllerID (and so had a SG of that name around to be successfully looked up). It's only recently that has been absent, and exposed this bug.
> fix #220, use correct controllerID looking up SGs

- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- controller.go
Two new flags have been implemented:
--logs-s3-bucket <name of s3 bucket>
--logs-s3-prefix <path prefix within s3 bucket>
Setting the bucket will enable logging support, not setting it will
leave it disabled. The prefix setting will only take effect if the
bucket is also set.
This should satisfy the feature request in #201
> Enable ALB logging to S3 via new flags

- deploy/README.md
- deploy/kops.md
- deploy/requirements.md
docs fix https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/213 update kops docs to match the policy that was stated
docs fix requirements.md to match our current deployment https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/cluster.yaml#L655-L717
> docs: fix policy

- Gopkg.toml
They both follow semver, so `~` is unnecessarily restrictive.
> Fix aws-sdk-go & testify dependencies

- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- controller.go
Added parameter `aws-waf-web-acl-id` (it must be the waf hash id, not the name) that when it is provided it will create an cludformation template with an WafAssociation
It will require the policies:
- waf-regional:AssociateWebACL
- waf-regional:DisassociateWebACL
- elasticloadbalancing:SetWebACL
Known issue, It won't disassociate in case of removal to any wafid
> #164 Added impl that provide waf id and create cf with waf association

- README.md
Old link is leading to a 404 page.
> Update link to skipper ingress controller docs

- Dockerfile
- Makefile
Drops the docker stage build as it's much slower because you need to pull the `golang` image on the CI and re-pull all dependencies as they are not cached by CDP.
You also need to re-pull dependencies every time when running locally.
> Drop Docker stage build to speed up build

- aws/adapter.go
- aws/adapter_test.go
- aws/asg.go
- worker.go
Fixes a bug introduced in #245 (https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/248) where only the clusterID prefix was checked, resulting in the controller collecting *ALL* ASGs in the account including those not part of the cluster.
Additionally it checks that the stack is ready before trying to update ingress or target groups. Before this would lead to errors until the stack was fully created in AWS.
> Correctly lookup asg clusterID ownership

- deploy/skipper_serviceaccount.yaml
fix the permissions, new skipper features require to find their skipper peers
> fix the permissions, new skipper features require 

- worker.go
- worker_test.go
It seems like we have a bug where shared ingresses can be added to an already non-shared stack owned by another ingress.
Need to add tests to validate that this is indeed a bug.
> Don't add others ingresses to already owned/non-shared stack

- go.mod
- go.sum
Fixes #269 
Update the AWS SDK version to be able to support the new IAM support in AWS EKS 1.14
> Updated AWS SDK version to support native IAM

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- aws/cloudwatch.go
- aws/cloudwatch_test.go
- cloudwatch.md
- controller.go
- deploy/ingress-serviceaccount.yaml
- go.mod
- go.sum
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/config_map.go
- kubernetes/config_map_test.go
- kubernetes/resource.go
- kubernetes/resource_test.go
- kubernetes/testdata/fixture02.json
- worker.go
- worker_test.go
This PR adds support for CloudWatch Alarm configuration (#271) for each load
balancer created by the controller. This is an opt-in feature. To use
it, the `--cloudwatch-alarms-config-map` CLI flag has to be set and
should be pointed to a ConfigMap that contains the alarm configuration.
If the ConfigMap does not exist or contains malformed data, the
controller will just ignore it. Check out `cloudwatch.md` for a full
documentation of the feature.
> Support for CloudWatch Alarm configuration

- .travis.yml
- go.mod
- go.sum
Update go to 1.13
Updating aws-sdk-go
Updating golangci-lint
> Updating go 1.13

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- controller.go
- go.mod
- go.sum
Implements the feature described in #199
Simply adds a controller flag, that if set, replaces the forward rule on the HTTPListener with a redirection rule to HTTPS, preserving the rest of the URL.
Note for reviewer: This did require me to update go-cloudformation (and it's dependencies), as `cloudformation.ElasticLoadBalancingV2ListenerRedirectConfig` was not present in the pinned version.
> implement an http-to-https redirect option

- aws/adapter.go
- kubernetes/adapter.go
This improves the handling of SSL policy in case the user specifies an invalid value in the annotation.
Before we would just check for valid SSL Policy on Stack creation and fall back to the default policy in case it wasn't valid. This had the problem that new stacks would be created again and again in case the policy was invalid because each newly created stack wouldn't satisfy the ingress with a different (invalid) SSL Policy defined.
Now we fall back to the default already when reading the ingress. Additionally we add a safer validation to the stack creation part where it will fail if the SSL Policy is invalid.
This is missing some form of error reporting for the users, but I think this should be handled in a separate PR e.g. by adding events.
> Better handling of invalid SSL Policy

- README.md
- aws/adapter.go
- aws/asg.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- worker.go
- worker_test.go
first part to support NLB #236
resource: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html 
Signed-off-by: Sandor Szuecs <sandor.szuecs@zalando.de>
> Add support for Network Load Balancers

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
- deploy/ingress-controller.yaml.example
- go.mod
- go.sum
Switch to kingpin as flag lib for simpler validation
Fix: #283
Also changed from variable names and removed unused flag `cf-custom-template`.
> Switch to kingpin as flag lib for simpler validation

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
This adds a flag `--nlb-http-enabled` which when set
to true it will create an HTTP listener (port 80) for Network Load
Balancers. This value is disabled by default for security reasons since
NLB can't support HTTP -> HTTPS redirection.
This also improves the README by documenting the different features
available for the two different load balancer types supported.
> Make HTTP support opt-in for Network Load Balancers

- aws/adapter.go
- aws/adapter_test.go
Fixes the filter parsing for ASG such that cluster IDs with `:` are
handled correctly.
> Fix parsing of custom filters for ASG filter

- deploy/ingress-serviceaccount.yaml
- deploy/skipper_serviceaccount.yaml
The kube-ingress-aws-controller doesnt startup any more because it errors out with
```
time="2020-02-20T14:57:51Z" level=error msg="doWork failed to list ingress resources: failed to get routegroup list: unexpected status code (Forbidden) for GET \"/apis/zalando.org/v1/routegroups\": {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"routegroups.zalando.org is forbidden: User \\\"system:serviceaccount:kube-system:kube-ingress-aws\\\" cannot list resource \\\"routegroups\\\" in API group \\\"zalando.org\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"group\":\"zalando.org\",\"kind\":\"routegroups\"},\"code\":403}\n"
```
> :bug: extending cluster role

- Makefile
By default make is not showing any possible options what one can run, this is a simple trick which uses comments by using and replaces it by using sed.
```console
$ make help
Usage:
clean          cleans the binary
test           runs go test
lint           runs golangci-lint
fmt            formats all go files
build.local    builds a local binary in build directory
build.local    builds a binary for linux/amd64 in build directory
build.osx      builds a binary for osx/amd64 in build directory
build.docker   builds docker image
build.push     pushes docker image to registry
recreate.ca    recreates a signed local test certificate
help           prints this help message
```
> Help usage for make

- README.md
- controller.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- worker.go
fix #308
- feature: add cluster.local to not create an ALB/NLB
- feature: update ingress/routegroup, in case you switch from public to only cluster.local host rules
> feature: support cluster.local 

- aws/adapter.go
- aws/cf.go
- aws/cf_test.go
- aws/cfmock_test.go
- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- worker.go
- worker_test.go
Add the ability to set a 'WAF Id' in ingress configuration as an annotation #238
WAF ACL id is set in annotations like below:
```zalando.org/aws-load-balancer-waf-id: "foobar"```
This would create a new loadbalancer and associate WAF if there is no loadbalancer with the same waf attached.
> Add per ingress WAF support

- controller.go
This makes it easier to see what version is running when looking at the K8s logs.
> Show version on boot

- aws/adapter.go
- controller.go
This makes it easier to debug issues, for example with [IMDSv2](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/309).
> AwsAdapter > Enable `LogDebugWithRequestErrors` when debug mode is enabled

- kubernetes/adapter.go
- kubernetes/client.go
Makes https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/328 obsolete. 
@mikkeloscar
> Handle 403 Forbidden responses when searching for RouteGroups

- aws/adapter.go
Updated list from:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
> Adds new ALB SSL policies

- aws/adapter.go
It's not used at all and it confuses everybody, see https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/339#issuecomment-610590907
It was removed in https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/111. 
I will followup on improvements as suggested in #339
/cc @szuecs
> Remove unused `stackTTL`

- controller.go
As discussed in https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/339
There is already a way for us to increase the TTL:
```go
kingpin.Flag("cert-ttl-timeout", "sets the timeout of how long a certificate is kept on an old ALB to be decommissioned.").
Default(defaultCertTTL).DurationVar(&certTTL)
```
This TTL is used to remove the old LB stack. It was set to 30 minutes and this PR will change it to 1 hour.
On our deployment, we will further increase this to 24 hours.
> Change default cert TTL to 1 hour

- .gitignore
- Makefile
- aws/cf_template.go
This fixes #331 by ensuring that the WAF ID parameter is ONLY set on the stack when the ID is not empty.
We accidentally set it optionally and by default in #341
> Ensure that WAF ID is really optional on the stack.

- .github/dependabot.yml
Enables the Github native version of dependabot as documented here: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically
Not completely sure how it's different from the @dependabot we currently have enabled. Let's try it out!
> Enable Github Native dependabot

- certs/matching_test.go
- go.mod
- go.sum
This updates the certificate tests to not rely on certs with the `CommonName` fields which has been deprecated in Go 1.15: https://golang.org/doc/go1.15#commonname
This make the tests pass with Go 1.15.
Additionally it updates dependencies.
> Update to Go 1.15 + dependencies update

- aws/adapter.go
- aws/cf.go
- controller.go
Adds a flag `--additional-stack-tags key=val` which allows setting additional custom tags on the CF stacks managed by the controller.
This can be useful if your infrastructure relies on additional tags e.g. for cost reporting or permissions. Zalando use case is to add `InfrastructureComponent=true` tags such that we can prevent non-admin users from touching resources with those tags.
> Add support for setting additional stack tags

- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
Allow configuring the [deregistration delay](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#deregistration-delay) via `--deregistration-delay-timeout`. The default is set to 5 minutes to match AWS.
> Make deregistration delay timeout configurable

- aws/adapter.go
- worker.go
`CreateStack` and `UpdateStack` used different values for the SG parameter, causing it to reset the configuration. Fix by making `UpdateStack` use the SG from the ingress if set, not the default one.
> UpdateStack(): don't reset the security group

- aws/adapter.go
- controller.go
- go.sum
Currently the controller gets `clusterID` and `vpcID` by looking up the information from the EC2 instance where it's running. This creates a hard dependency where the controller MUST run on an EC2 instance where the metadata endpoint is available.
This introduces a way to run the controller in other environment e.g. Fargate (#375)  by introducing two flags `--cluster-id` and `--vpc-id` which when specified, omits the logic for looking up this information from the EC2 instance.
As a bonus this makes it easier to test the controller because it can be run locally pointing to a cluster/AWS account.
Fix #375
> Make running on EC2 optional

- aws/asg.go
- aws/asg_test.go
- controller.go
In some cases the Autoscaling groups can end up being configured with target groups that no longer exists. If that happens we have logic for cleaning up those target groups to prevent other autoscaling group changes from being blocked.
This fixes the logic slightly such that it doesn't try to get the tags of non-existing target groups which would fail and thus prevent the controller from detaching the non-existing target groups.
> Fix detaching of target groups

- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- cloudformation.md
- controller.go
The Health-Check Timeout is currently unconfigured, resulting into `5s`
However, in order to reduce the `healthcheck Interval` below `6s` it is necessary to also reduce the `Timeout` as it must be smaller!
Otherwise following exception will occur:
```
Health check interval must be greater than the timeout. (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; ...)
```
This adds a paramter that can be configured.
> ✨ adding parameter for Health-Check Timeout

- aws/cf_template.go
- aws/cf_template_test.go
For some reason custom healthcheck timeout is not supported when target group uses TCP protocol. This is the error shown in Cloudformation when creating an NLB:
```
Custom health check timeouts are not supported for health checks for target groups with the TCP protocol (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: InvalidConfigurationRequest; Request ID: xxx; Proxy: null)
```
Fix it by only setting custom healthcheck timeout when `protocol != TCP`
> Don't set healthcheck timeout on NLB

- README.md
- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
This commit addresses #402. It adds the following new configuration
flags:
- internal-domains
- deny-internal-domains
- deny-internal-domains-response
- deny-internal-domains-response-content-type
- deny-internal-domains-response-status-code
The main flag is the `deny-internal-domains`, a boolean that enables and
disables the feature. The other flags allow to set the internal domains
that will be protected as well as the response that will be returned.
Defaults are also set: an HTTP `text/plain` `401 - Unauthorized`
response for the `*.ingress.cluster.local` domain.
The ALB cloudformation template will add a
[`AWS::ElasticLoadBalancingV2::ListenerRule`][0] resource, configured
with the [condition][1] values from the `internal-domains` and the
[action `fixedresponseconfig`][2] with the …
> ALB Listener rule to deny internal domain requests

- aws/cf_template.go
- aws/cf_template_test.go
The #400 PR added rules to deny internal traffic, and in its docs it
even stated that NLBs do not support this feature. But the code didn't
check for the load balancer type. This commit adds the logic to apply
the rule creation just for ALBs.
> Apply rule creation just on ALBs

- README.md
This commit fixes the usage indication of the `--deny-internal-domain`.
[Kingpin][0] generates a negation flag instead of supporting the values
`true` or `false`.
[0]: https://github.com/alecthomas/kingpin
> Fix README on deny internal domains usage

- README.md
- aws/adapter.go
- aws/adapter_test.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
This adds a boolean flag called `target-https` which will set the
protocol used on a target group to HTTPS.
**Motivation**
AWS VPC networking does prevent external targets from sniffing the wire,
but if the target is a proxy listening on the hostNetwork, any other pod
deployed to that node that is also using the hostNetwork can read the traffic
unencrypted. In cases where end-to-end encryption is expected or
desirable, this allows for that option.
> Add the ability to use an HTTPS target

- aws/adapter.go
I missed the different stackSpec setup for the CreateStack method, and
only added for UpdateStack. Side effect is that new stacks would always
still have a HTTP target group, but stack updates would change it to
HTTPS if specified.
Signed-off-by: Jeremy Huntwork <jhuntwork@lightcubesolutions.com>
> :bug: Add possible HTTPS support on new stacks

- kubernetes/adapter.go
- kubernetes/adapter_test.go
- kubernetes/ingress.go
- kubernetes/ingress_test.go
- kubernetes/routegroup.go
- kubernetes/routegroup_test.go
Update of ingress or routegroup load balancer requires only namespace and name
parameters while hostname change check could be performed upfront.
The change removes unnecessary mapping to the internal structures `*ingress` and `*routegroup`.
This also simplifies "roundtrip" ingress mapping test into just "forward"
which enables testcases for empty annotations.
> Refactors kubernetes adapter `UpdateIngressLoadBalancer` method

- aws/cf_template.go
- aws/cf_template_test.go
Followup on https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/411#discussion_r708516996
* Inlined well-known constants (HTTP, HTTPS, TCP, TLS)
* Added explicit load balancer type checks for both HTTP and HTTPS listeners
* Moved target group protocol and health check protocol selection close to target group construction
> HTTPListener uses HTTP protocol when target is HTTPS

- .gitignore
- aws/adapter.go
- aws/asg.go
- aws/asg_test.go
- aws/asgmock_test.go
- worker.go
When controller attempts to attach a batch of target groups that
contains nonexistent target group (could be deleted manually by mistake)
to the autoscaling group the attempt fails to pass validation which
prevents attachment of the other valid target groups from the batch.
Also:
* Improves error log messages
* Adds processChunked helper function
* Adds describeTargetGroups
* Fixes `detachARNs`/`validARNs` slices' capacity
> Do not attach nonexistent target groups

- aws/adapter.go
- aws/adapter_test.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
Healthy threshold: The number of consecutive health checks successes required before considering an unhealthy target healthy
This configuration is required since the default of "5" time the interval, which is minimum of 6s, sums up to 30s that is too long delay in our configurations.
Signed-off-by: Samuel Lang <gh@lang-sam.de>
> adding config option for ALB & NLB healthy threshold count

- README.md
- kubernetes/adapter.go
- kubernetes/adapter_test.go
default NLB with internal annotation should fallback to ALB, because of https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#intermittent-connection-failure that we also found in a small production incident
> default NLB with internal annotation should fallback to ALB

- aws/adapter.go
fixes: #475
Given that there is only one TG and it is of type IP created by the stack, we are not callling `updateTargetGroupsForAutoScalingGroup` -> `detachTargetGroupsFromAutoScalingGroup`
This possible solution is to move this guard inside `updateTargetGroupsForAutoScalingGroup` - see https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/475#issuecomment-1033827245
However, the  guard introduced in #141 is practically present now inside `updateTargetGroupsForAutoScalingGroup`  introduced by #436 and therefore we can simply remove it.
Tested in lab clusters.
Signed-off-by: Samuel Lang <gh@lang-sam.de>
> clean up invalid target groups

- kubernetes/adapter.go
In case we got any error listing `RouteGroups` or `FabricGateways` we would disable support assuming the resource is not available in the cluster.
This means that the feature can get disabled e.g. if the api-server is unavailable which was not the intention.
Fix the logic to only disable the features on specific errors: `NotFound` (404) and `NoAccess` (403).
> Only disable 'excotic' features on NotFound/NoAccess errors

- aws/cf.go
- aws/cf_test.go
- worker.go
Stack update may fail due to external changes, e.g. due to removal of
a referenced security group.
This change reports certain stack statuses as problems which prevents
`last_sync_timestamp_seconds` metric update that could be
used to monitor stack update failures.
> worker: check cloudformation stack status

- delivery.yaml
Multi-arch build (#517) for the prod-build step didn't work because it was still using the legacy CDP overlay. Change to cdp-runtime and get latest Go version as well.
> Used cdp-runtime/golang for prod build

- .golangci.yml
remove golint because project is archived deprecated for a while and staticcheck covers IMO everything we need
> remove golint because project is archived

- .github/workflows/ci.yaml
- .golangci.yml
- aws/acm.go
- aws/adapter.go
- aws/asg.go
- aws/cf.go
- aws/iam.go
- aws/mocks_test.go
- kubernetes/client_test.go
- kubernetes/config_map_test.go
- kubernetes/ingress_test.go
- kubernetes/pods_test.go
- kubernetes/routegroup_test.go
- worker.go
This updates golangci-lint to always use the latest version on github-actions. It also ~drops the `.golangci.yml` config and uses the default settings which adds new and previously suppressed linters~ updates the `.golangci.yml` to have the list of current default linters from golangci-lint.
Lastly it addresses all the lint errors identified.
> Update golanci-lint and address suggestions

- worker.go
- worker_test.go
By default adding a WAF ACL ID or a security group etc. to an ingress/routegroup would require the creation of a new load balancer. This makes sense for the cases where the load balancer is shared by multiple ingresses/routegroups but for those load balancers only owned by a single resource (via `zalando.org/aws-load-balancer-shared=false`) it doesn't really make sense to create a new load balancer when the setting is just adding/changing a security group, WAF ACL or the TLS settings which can be done in-place on a running LB.
This PR handles the above case so we reduce the situations where a new load balancer needs to be created.
> Allow changing settings on an owned LB

- kubernetes/client.go
Follow up to #551 which was missing the service account token file path when getting the token from the secretsReader.
> Use full path for token file

- README.md
Add a bit of documentation on how to run the controller outside of EC2
Follow up to #376 and https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/455#issuecomment-1398178962
> Document how to run outside of EC2

- aws/adapter.go
This adds support for the following:
ELBSecurityPolicy-TLS13-1-2-2021-06
ELBSecurityPolicy-TLS13-1-2-Res-2021-06
ELBSecurityPolicy-TLS13-1-2-Ext1-2021-06
ELBSecurityPolicy-TLS13-1-2-Ext2-2021-06
ELBSecurityPolicy-TLS13-1-1-2021-06
ELBSecurityPolicy-TLS13-1-0-2021-06
ELBSecurityPolicy-TLS13-1-3-2021-06
See: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
> Add 2021-06 elb security policies.

- go.mod
- go.sum
Update to github.com/emicklei/go-restful 2.16.0 to address vulnerability.
> Update to github.com/emicklei/go-restful 2.16.0

- aws/adapter_test.go
Found via `deadcode -test ./...`
See https://pkg.go.dev/golang.org/x/tools/internal/cmd/deadcode
> aws: fix test name

- aws/acm.go
- aws/acm_test.go
- aws/adapter.go
- aws/fake/acm.go
- aws/fake/iam.go
- aws/iam.go
- aws/iam_test.go
- controller.go
This feature aims to enable `kube-ingress-aws-controller` to ignore certificates based on tags. Effectively what this means is, you can specify a tag through the command line and the ingress controller will only use IAM/ACM certificates that have that specific tag when matching the host to define which certificate is more appropriate to add to the LB.
If a tag is not specified the ingress controller shall pick all available certificates for matching.
The main idea behind this feature is to make it very specific which certificates should be considered, this feature does not avoid incidents, but make it clearer to operators which certificates are being considered in the matching phase.
This PR addresses the issue: https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/652
> Add option to filter certificates by tag before adding it to LB

- .zappr.yaml
Option needs to be also enabled from Zapper settings
Signed-off-by: Mustafa Abdelrahman <mustafa.abdelrahman@zalando.de>
> Require labels

- aws/cf_test.go
- aws/fake/cf.go
If a CloudFormation stack is in `ROLLBACK_IN_PROGRESS` it returns no output, hence no target groups. While CloudFormation is working to get the stack back the controller may send traffic to LBs without TG.
This PR is trying to replicate this behaviour, current state means that we also collect stacks in this state which we shouldn't do.
> Add test case for rolling in progress stacks

- controller.go
Fixes #678
With the removal of the `--ingress-api-version` flag in 0.15.0, this value was no longer set and the constructed api URL is incomplete.
> Set the default ingress API Version

- controller_test.go
Initial step to add tests to controller and get rid of kingpin, currently testing these flags isn't very flexible. Maybe we need to adopt something similar to skipper.
> testsuit: add test case for flags

- aws/adapter.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- controller.go
- controller_test.go
- testdata/ingress_nlb/input/k8s/ing.yaml
- testdata/ingress_nlb/output/templates/ing.cf
- testdata/ingress_rg_shared_nlb/output/templates/shared.cf
- testdata/rg_nlb/output/templates/rg.cf
- worker_test.go
feature: set nlb zone affinity for clients
log: log default cross zone and zone affinity config
This enables you to set dns_record.client_routing_policy configuration, such that you can decide for NLB via R53 feature that clients running in the same zone will hit also the same zone of your NLB. This is interesting for cross cluster traffic or traffic that stays in the same cluster but passes the NLB. Valid configurations are:
- availability_zone_affinity
- partial_availability_zone_affinity
- any_availability_zone (default)
see also https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html\#load-balancer-attributes and https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html\#zonal-dns-affinity
> Feature: nlb zone affinity via r53

- README.md
> doc: zone aware traffic

- delivery.yaml
Use static base image which is similar to gcr.io/distroless/static
See previous #699
> deploy: use static base image

- controller.go
- delivery.yaml
Pass correct version to multiacrh build targets.
Follow up on #517
> build: use correct version for multiarch image

- aws/acm.go
- aws/acm_test.go
- aws/fake/acm.go
`getACMCertificateSummaries` did not check `ListCertificatesPages` error
and returned empty `CertificateSummary` slice and no error
via `filterCertificatesByTag` if `filterTag` is configured.
Empty `CertificateSummary` results in empty `existingStackCertificateARNs`
for each `loadBalancer` model which triggered stack update:
```
level=info msg="Updating \"internet-facing\" stack for 0 certificates / 0 ingresses"
```
and then stack deletion on the next cycle:
```
level=info msg="Deleted orphaned stack \"kube-ingress-aws-controller-aws-XXX\""
```
due to empty certificate tags after previous update.
Follow up on https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/658
> aws: fail on ListCertificatesPages error

- worker_test.go
```console
$ staticcheck ./...
worker_test.go:21:2: package "github.com/zalando-incubator/kube-ingress-aws-controller/aws" is being imported more than once (ST1019)
worker_test.go:22:2: other import of "github.com/zalando-incubator/kube-ingress-aws-controller/aws"
```
> Fix staticcheck warning

- certs/fake/certificate.go
- worker_test.go
Refactor fake certificate provider to enable creation of multiple certificates with the same CA and to allow manual mocking of GetCertificates result.
Follow up on #615 and #587
> certs/fake: refactor CertificateProvider

- aws/acm.go
- testdata/no_certificates/input/k8s/ing.yaml
- worker.go
- worker_test.go
Controller manages loadbalancer lifecycle based on available certificates.
Prevent controller from deleting loadbalancers when there are no certificates found e.g. due to a bug like #725 or a tag filter misconfiguration (#658).
> worker: fail on missing certificates

- .github/workflows/ci.yaml
- .gitignore
- aws/adapter.go
- aws/adapter_test.go
- aws/cf.go
- aws/cf_template.go
- aws/cf_template_test.go
- aws/cloudwatch.go
- aws/cloudwatch_test.go
- aws/elbv2.go
- aws/elbv2_test.go
- aws/fake/elbv2.go
- cloudformation.md
- testdata/ing_shared_rg_notshared_alb/output/templates/01-ing.cf
- testdata/ing_shared_rg_notshared_alb/output/templates/02-rg.cf
- testdata/ingress_alb/output/templates/ing.cf
- testdata/ingress_nlb/output/templates/ing.cf
- testdata/ingress_rg_shared_alb/output/templates/shared.cf
- testdata/ingress_rg_shared_nlb/output/templates/shared.cf
- testdata/rg_alb/output/templates/rg.cf
- testdata/rg_nlb/output/templates/rg.cf
- worker.go
- worker_test.go
As per the existing behavior, once the stack update completes, the ingress controller immediately updates the status of all ingresses and routegroups to reference the new load balancer. This update may sometimes happens before the new load balancer has marked its targets (skipper-ingress) as healthy, leading clients being routed to a load balancer that is not ready to serve traffic yet.
To improve this behavior we retrieve the ELBs via AWS API and build the models including the ELB states of the corresponding ELBs. Then before updating the ingresses/routegroups (updateIngress func) we check whether the ELB is in active state, if not we skip updating the ingresses/routegroups status with the ELB hostname.
> ingress-controller: update ingresses only if the load balancer is active

- aws/adapter.go
- aws/adapter_test.go
Adapter.FindLBSubnets method is used to specify stack subnets and becomes a parameter of a CloudFormation template.
This change returns sorted result to avoid sporadic changes to CloudFormation template that triggers update of CloudFormation stack and corresponding LoadBalancer Subnets.
Though LoadBalancer Subnets update does not require interruption as per https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnets there is no reason to trigger any unneccessary updates.
Related to https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/454
> aws: sort subnets in Adapter.FindLBSubnets

- controller.go
- metrics.go
- worker.go
- worker_test.go
Add worker struct to hold references to adapters, metrics and configuration values and convert functions into its methods to avoid using global variables and passing a lot of parameters around.
The only global variable still in use is `firstRun` ~hacked~ introduced by #258
> Add worker type

- Makefile
- aws/adapter.go
- aws/adapter_test.go
- aws/elbv2.go
- aws/elbv2_test.go
- certs/fake/certificate.go
- controller.go
- go.mod
- go.sum
- internal/aws/mock/mock.go
- internal/kubernetes/mock/mock.go
- kubernetes/adapter.go
- minloadbalancerage_test.go
- worker.go
- worker_test.go
Within https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/748 the controller was improved to wait until loadbalancer state becomes "active" before updating ingress status which triggers traffic switch to the new loadbalancer (e.g. via external-dns).
It turns out that while new loadbalancer state is active its target groups may not have discovered targets yet.
This change delays ingress status update for a new loadbalancer to give its target groups time to discover targets. The delay is configured by a new `min-loadbalancer-age` flag. Default value was chosen after testing in an AWS account.
The more elaborate alternative is to call `describe-target-health` and check `TargetHealthDescriptions`.
Other changes:
* unexport loadbalancer state fields
* make loadbalancer state …
> worker: delay ingress status update for new load balancers
